const profileImage='assets/somnath-profile.jpg';
const profileFallback='https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=1200&q=85';
const heroArt=document.querySelector('.hero-art');
const heroImage=document.createElement('img'); heroImage.className='profile-image hero-profile-image'; heroImage.src=profileImage; heroImage.alt='Portrait of Somnath Mishra'; heroImage.onerror=()=>{heroImage.onerror=null;heroImage.src=profileFallback}; heroArt.prepend(heroImage);
const aboutVisual=document.querySelector('.dna-graphic');
aboutVisual.className='profile-card reveal'; aboutVisual.setAttribute('aria-label','Somnath Mishra profile portrait'); aboutVisual.innerHTML=`<img class="profile-image about-profile-image" src="${profileImage}" alt="Portrait of Somnath Mishra"><span class="profile-card-label">Somnath Mishra / Profile</span>`;
const aboutImage=aboutVisual.querySelector('.about-profile-image'); aboutImage.onerror=()=>{aboutImage.onerror=null;aboutImage.src=profileFallback};
const skills=[{title:'Programming',items:['Python','C','Java','Web development']},{title:'Bioinformatics',items:['Computational biology','Sequence analysis','Biological data','Bioinformatics tools']},{title:'Biotechnology',items:['PCR','Gel electrophoresis','Spectrophotometry','Chromatography','Tissue culture','Fermentation']},{title:'Data & technology',items:['Data analysis','Visualization','Problem solving','Git / GitHub','HTML · CSS · JS']}];
const projects=[
 {id:'01',title:'AI Medical Report Analyzer',category:'AI / Data / Healthcare',filters:['data','development'],desc:'An intelligent concept for analyzing medical reports and presenting complex information in a simpler, structured format.',tech:'Python · Data Analysis · AI Concepts',visual:'medical-report.svg'},
 {id:'02',title:'Smart Water Bottle',category:'IoT / Sensors / Biotechnology',filters:['iot','biotech'],desc:'A smart water-monitoring concept integrating sensors and microcontroller technology to encourage better hydration tracking.',tech:'Arduino · Sensors · Embedded Systems',visual:'smart-water-bottle.svg'},
 {id:'03',title:'Arduino Sensor Monitoring System',category:'IoT / Electronics',filters:['iot','development'],desc:'A sensor-based monitoring project involving temperature and distance measurement using LM35 and ultrasonic sensors.',tech:'Arduino · LM35 · Ultrasonic Sensor',visual:'sensor-monitor.svg'},
 {id:'04',title:'Bioinformatics Data Exploration',category:'Bioinformatics / Python',filters:['bioinformatics','data'],desc:'A computational biology project exploring how programming can assist with biological data processing and analysis.',tech:'Python · Bioinformatics · Data Analysis',visual:'bioinformatics-data.svg'},
 {id:'05',title:'Environmental Biotechnology Research',category:'Research / Biotechnology',filters:['research','biotech'],desc:'A research-oriented project exploring biotechnology applications in environmental sustainability, including bioremediation and water purification.',tech:'Research · Sustainability · Biotechnology',visual:'environmental-research.svg'},
 {id:'06',title:'Algae & Biofuel Research',category:'Biotechnology / Research',filters:['research','biotech'],desc:'An exploration of the role of algae in sustainable biofuel production and its potential contribution to renewable energy.',tech:'Biotechnology · Research · Sustainability',visual:'algae-biofuel.svg'}
];
const skillGrid=document.querySelector('#skill-grid'); skillGrid.innerHTML=skills.map((skill,i)=>`<article class="skill-card reveal"><b>0${i+1}</b><h3>${skill.title}</h3><div class="tag-row">${skill.items.map(item=>`<span>${item}</span>`).join('')}</div></article>`).join('');
const projectGrid=document.querySelector('#project-grid');
function renderProjects(filter='all'){const shown=projects.filter(p=>filter==='all'||p.filters.includes(filter));projectGrid.innerHTML=shown.map(p=>`<article class="project-card reveal visible" data-id="${p.id}"><div class="project-visual"><img src="assets/${p.visual}" alt="${p.title} project visual" loading="lazy"><span class="art-label">PROJECT / ${p.id}</span></div><div class="project-meta"><span>${p.id} / ${p.category}</span><span>↗</span></div><h3>${p.title}</h3><p>${p.desc}</p><span class="project-link">View project →</span></article>`).join(''); projectGrid.querySelectorAll('.project-card').forEach(card=>card.addEventListener('click',()=>openModal(projects.find(p=>p.id===card.dataset.id))));}
renderProjects();
document.querySelectorAll('.filter').forEach(button=>button.addEventListener('click',()=>{document.querySelector('.filter.active').classList.remove('active');button.classList.add('active');renderProjects(button.dataset.filter)}));
const modal=document.querySelector('#project-modal'); const modalContent=document.querySelector('#modal-content');
function openModal(project){modalContent.innerHTML=`<p class="modal-kicker">Project ${project.id} / ${project.category}</p><h2>${project.title}</h2><p>${project.desc}</p><div class="modal-details"><div><small>Objective</small><span>Explore a practical intersection of science, technology and problem solving.</span></div><div><small>Technologies</small><span>${project.tech}</span></div><div><small>Learning outcome</small><span>Translate a concept into a clearer, more structured technical direction.</span></div><div><small>Status</small><span>Concept / portfolio case study</span></div></div>`;modal.showModal();}
document.querySelector('.modal-close').addEventListener('click',()=>modal.close());modal.addEventListener('click',e=>{if(e.target===modal)modal.close()});
const header=document.querySelector('.site-header');window.addEventListener('scroll',()=>header.classList.toggle('scrolled',window.scrollY>30));
const menuButton=document.querySelector('.menu-toggle'),nav=document.querySelector('.main-nav');menuButton.addEventListener('click',()=>{const open=nav.classList.toggle('open');menuButton.setAttribute('aria-expanded',open)});nav.querySelectorAll('a').forEach(link=>link.addEventListener('click',()=>{nav.classList.remove('open');menuButton.setAttribute('aria-expanded','false')}));
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
const form=document.querySelector('#contact-form');form.addEventListener('submit',event=>{event.preventDefault();const status=form.querySelector('.form-status');if(!form.checkValidity()){status.textContent='Please complete all fields with a valid email.';form.reportValidity();return}status.textContent='Thanks. This form is ready to connect to your preferred email service.';form.reset()});
document.querySelectorAll('[data-placeholder-link]').forEach(link=>link.addEventListener('click',event=>{event.preventDefault();alert('Add Somnath’s LinkedIn or GitHub URL in index.html to activate this link.')}));
const cursor=document.querySelector('.cursor');if(cursor){window.addEventListener('mousemove',e=>{cursor.style.left=`${e.clientX-4}px`;cursor.style.top=`${e.clientY-4}px`});document.querySelectorAll('a,button,.project-card').forEach(el=>{el.addEventListener('mouseenter',()=>cursor.classList.add('is-hover'));el.addEventListener('mouseleave',()=>cursor.classList.remove('is-hover'))})}
