const profileImage='assets/somnath-profile.jpg';
const themeToggle=document.querySelector('.theme-toggle');
const savedTheme=localStorage.getItem('portfolio-theme');
if(savedTheme==='dark'){document.body.classList.add('dark-theme')}
function updateThemeToggle(){const dark=document.body.classList.contains('dark-theme');themeToggle.setAttribute('aria-label',dark?'Switch to light theme':'Switch to dark theme');themeToggle.setAttribute('aria-pressed',dark);themeToggle.title=dark?'Switch to light theme':'Switch theme';themeToggle.querySelector('.theme-icon').textContent=dark?'☀':'☾'}
updateThemeToggle();
themeToggle.addEventListener('click',()=>{const dark=document.body.classList.toggle('dark-theme');localStorage.setItem('portfolio-theme',dark?'dark':'light');updateThemeToggle()});
const profileFallback='https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=1200&q=85';
const heroArt=document.querySelector('.hero-art');
const heroImage=document.createElement('img'); heroImage.className='profile-image hero-profile-image'; heroImage.src=profileImage; heroImage.alt='Portrait of Somnath Mishra'; heroImage.onerror=()=>{heroImage.onerror=null;heroImage.src=profileFallback}; heroArt.prepend(heroImage);
const aboutVisual=document.querySelector('.dna-graphic');
aboutVisual.className='profile-card reveal'; aboutVisual.setAttribute('aria-label','Somnath Mishra profile portrait'); aboutVisual.innerHTML=`<img class="profile-image about-profile-image" src="${profileImage}" alt="Portrait of Somnath Mishra"><span class="profile-card-label">Somnath Mishra / Profile</span>`;
const aboutImage=aboutVisual.querySelector('.about-profile-image'); aboutImage.onerror=()=>{aboutImage.onerror=null;aboutImage.src=profileFallback};
const skills=[{title:'Programming',items:['Python (Beginner–Intermediate)','C Programming (Intermediate)','R Language (Learning)']},{title:'Data analysis',items:['Microsoft Excel (Intermediate)','Data Analysis & Visualization','Pivot Tables & Charting']},{title:'Analytical strengths',items:['Analytical Thinking','Problem Solving','Structured Reporting']},{title:'Languages',items:['Hindi (Fluent)','English (Working Proficiency)']}];
const projects=[
 {id:'01',title:'Sales Data Analysis',category:'Excel / Data Analysis',filters:['data'],desc:'A self-initiated Excel analysis that segments sales by category, region and time period to support comparison and insight generation.',tech:'Microsoft Excel · Pivot Tables · Charting · Conditional Formatting',visual:'bioinformatics-data.svg'},
 {id:'02',title:'AI-Powered CT Scan Analyzer',category:'AI / Web Application',filters:['development','research'],desc:'A group project web application that analyzes CT scan images with artificial intelligence and turns model outputs into clinician-readable reports.',tech:'Artificial Intelligence · Web Application · Clinical Reporting',visual:'medical-report.svg'},
 {id:'03',title:'AI-Powered Smart Water Bottle',category:'Arduino / Health IoT',filters:['iot','biotech'],desc:'A group project using an Arduino Nano, water-level sensors and a real-time clock to encourage consistent hydration through audiovisual alerts.',tech:'Arduino Nano · Water Level Sensors · RTC',visual:'smart-water-bottle.svg'}
];
const skillGrid=document.querySelector('#skill-grid'); skillGrid.innerHTML=skills.map((skill,i)=>`<article class="skill-card reveal"><b>0${i+1}</b><h3>${skill.title}</h3><div class="tag-row">${skill.items.map(item=>`<span>${item}</span>`).join('')}</div></article>`).join('');
const projectGrid=document.querySelector('#project-grid');
function renderProjects(filter='all'){const shown=projects.filter(p=>filter==='all'||p.filters.includes(filter));projectGrid.innerHTML=shown.map(p=>{const image=p.visual==='smart-water-bottle.svg'?'':`<img src="assets/${p.visual}" alt="${p.title} project visual" loading="lazy" onerror="this.style.display='none'">`;return `<article class="project-card reveal visible" data-id="${p.id}"><div class="project-visual">${image}<span class="art-label">PROJECT / ${p.id}</span></div><div class="project-meta"><span>${p.id} / ${p.category}</span><span>↗</span></div><h3>${p.title}</h3><p>${p.desc}</p><span class="project-link">View project →</span></article>`}).join(''); projectGrid.querySelectorAll('.project-card').forEach(card=>{const image=card.querySelector('img');if(image){image.addEventListener('error',event=>{event.currentTarget.style.display='none'})}card.addEventListener('click',()=>openModal(projects.find(p=>p.id===card.dataset.id)))});}
renderProjects();
document.querySelectorAll('.filter').forEach(button=>button.addEventListener('click',()=>{document.querySelector('.filter.active').classList.remove('active');button.classList.add('active');renderProjects(button.dataset.filter)}));
const modal=document.querySelector('#project-modal'); const modalContent=document.querySelector('#modal-content');
function openModal(project){modalContent.innerHTML=`<p class="modal-kicker">Project ${project.id} / ${project.category}</p><h2>${project.title}</h2><p>${project.desc}</p><div class="modal-details"><div><small>Objective</small><span>Explore a practical intersection of science, technology and problem solving.</span></div><div><small>Technologies</small><span>${project.tech}</span></div><div><small>Learning outcome</small><span>Translate a concept into a clearer, more structured technical direction.</span></div><div><small>Status</small><span>Concept / portfolio case study</span></div></div>`;modal.showModal();}
document.querySelector('.modal-close').addEventListener('click',()=>modal.close());modal.addEventListener('click',e=>{if(e.target===modal)modal.close()});
const header=document.querySelector('.site-header');window.addEventListener('scroll',()=>header.classList.toggle('scrolled',window.scrollY>30));
const menuButton=document.querySelector('.menu-toggle'),nav=document.querySelector('.main-nav');menuButton.addEventListener('click',()=>{const open=nav.classList.toggle('open');menuButton.setAttribute('aria-expanded',open)});nav.querySelectorAll('a').forEach(link=>link.addEventListener('click',()=>{nav.classList.remove('open');menuButton.setAttribute('aria-expanded','false')}));window.addEventListener('resize',()=>{if(window.innerWidth>900){nav.classList.remove('open');menuButton.setAttribute('aria-expanded','false')}});
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
const form=document.querySelector('#contact-form');form.addEventListener('submit',event=>{event.preventDefault();const status=form.querySelector('.form-status');if(!form.checkValidity()){status.textContent='Please complete all fields with a valid email.';form.reportValidity();return}status.textContent='Thanks. This form is ready to connect to your preferred email service.';form.reset()});
const cursor=document.querySelector('.cursor');if(cursor){window.addEventListener('mousemove',e=>{cursor.style.left=`${e.clientX-4}px`;cursor.style.top=`${e.clientY-4}px`});document.querySelectorAll('a,button,.project-card').forEach(el=>{el.addEventListener('mouseenter',()=>cursor.classList.add('is-hover'));el.addEventListener('mouseleave',()=>cursor.classList.remove('is-hover'))})}
